### ISSUE TITLE
This is awesome!

### ISSUE THREAD

**Issue by luckman212** [vitorgalvao/tape#1]
@vitorgalvao This is such an awesome idea! Thanks for this 🏆

**Comment by vitorgalvao** [comment]
Been meaning to reply to this from the day you opened it. You’re probably the first person who discovered it organically!

Pretty great that the first comment on a new project are words of thanks, so thank you!

Quick info about the future of the project. I built this to scratch an itch, and scratch it it does! Regarding functionality, this is done. I’ll fix reported bugs but new features I’ll consider only if they’re dead simple to maintain or provide immense value.

As for the definitions on how to backup stuff, I welcome more via PRs. Since I built this for my itch, I’ve only added ones I care about or had collected years ago when this was still a bunch of blocks of code scattered in a file.

Again, thank you for taking the time to open this issue.

**Comment by 0xdevalias** [comment]
Just wanted to throw some more 🖤 on this thread. This is the type of thing i've wanted to add better support for in my [dotfiles](https://github.com/0xdevalias/dotfiles/issues/24) for a while now; and just happened to randomly stumble across it today via your alfred workflows. Many thanks!
