### ISSUE TITLE
How does it compare to mackup?

### ISSUE THREAD

**Issue by devnoname120** [vitorgalvao/tape#3]
https://github.com/lra/mackup

**Comment by vitorgalvao** [comment]
Depends on how you compare it. If you compare by raw number of supported software, right now Tape has fewer definitions than Mackup[^1] but can support considerably more.

I am aware of Mackup and [contributed regularly for a few years](https://github.com/lra/mackup/pull/213#issuecomment-123909998). But Mackup’s strategy [doesn’t work for Mac App Store apps](https://github.com/lra/mackup/issues/154), of which I have several. Plus, Mackup replaces and symlinks configurations while Tape copies them over and can keep several contained backups.

There are likely several other differences, particularly in behaviour, but I can’t attest to those because I haven’t used Mackup in many years.

I don’t care much for the “how does it compare” question because it feels like I’m being asked to trash talk another’s work. Tape isn’t competing with other tools, they can all coexist. I built it because none other worked like I want, but that doesn’t mean this solution is best for everyone. If you care how they compare, you should try them both and see which fits *you* better.

[^1]: Which might remain true unless I get PRs. [I built this to scratch my own itch](https://github.com/vitorgalvao/tape/issues/1#issuecomment-1040926375).
