### ISSUE TITLE
Tape Doesn't Back Up Trackpad & Keyboard Settings

### ISSUE THREAD

**Issue by oushima** [vitorgalvao/tape#4]
Hey,

I was trying out the program, but it doesn't save Keyboard Settings.
I tried making a backup on User 1 with certain keyboard preferences, and then I restored them on User 2.

After that I checked the macOS Settings for Keyboard on User 2, to see if the changes have been reflected. 
But they were not.

It also says that it backs up the Trackpad settings, but when I back them up on User 1 and restore them on User 2, the settings don't apply.

I also made sure to double check after rebooting my computer.

Could you please add this support?

Thank you in advance.

Kind regards.

Terminal info:
```
school@Denniss-MacBook-Pro Tape % tape restore 2024-05-08.tgz
Restoring backup for 1Password…
1Password is running. You may need to restart it for settings to take effect.
Restoring backup for Finder…
Finder is running. You may need to restart it for settings to take effect.
Restoring backup for macOS Fonts…
Restoring backup for macOS Sounds…
Restoring backup for macOS Spelling…
Restoring backup for macOS Trackpad…
Restoring backup for Messages…
Restoring backup for Tape…
Restoring backup for Zsh…
school@Denniss-MacBook-Pro Tape % 
```

**Comment by vitorgalvao** [comment]
> it doesn't save Keyboard Settings.

I don’t remember exactly why I didn’t add support, but I think it was because those settings are scattered.

> It also says that it backs up the Trackpad settings, but when I back them up on User 1 and restore them on User 2, the settings don't apply.

Looks like some are, some aren’t. Apple keeps breaking stuff like this, so I’ll just remove that definition. I have no desire to waste more time getting that to work when realistically it’s a couple of settings that only matters once in a blue moon when doing a clean install. The math doesn’t work out.

I’m receptive to pull requests and issues that share insight on the problems and help find solutions.
